name: dotnet lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install dotnet-format
        run: dotnet tool update -g dotnet-format

      - name: Run dotnet format
        run: dotnet format ./editorconfigExample.sln --verify-no-changes --verbosity diagnostic
